import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AlertTriangle, ArrowLeft, LockKeyhole, UserRoundCog } from "lucide-react";
import { AppShell } from "@/components/nex/AppShell";
import { AccountView, CampaignsView, ClientsView, CreativesView, CreditsView, FinanceView, MasterFinanceView, MasterOverview, Overview, SettingsView, UsersView } from "@/components/nex/DashboardViews";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const Route=createFileRoute("/demo")({head:()=>({meta:[{title:"Demonstração completa — NEX Ads"},{name:"description",content:"Explore todas as telas das áreas Cliente e Master do NEX Ads."},{property:"og:title",content:"Demonstração completa — NEX Ads"},{property:"og:description",content:"Explore todas as telas das áreas Cliente e Master do NEX Ads."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:DemoPage});

const screens={
 overview:{title:"Visão geral",subtitle:"Acompanhe a performance consolidada das suas campanhas.",master:false,view:<Overview/>},
 campaigns:{title:"Campanhas",subtitle:"Dados sincronizados em modo somente leitura.",master:false,view:<CampaignsView/>},
 credits:{title:"Créditos Meta",subtitle:"Consulte o saldo e acompanhe operações de recarga.",master:false,view:<CreditsView/>},
 finance:{title:"Financeiro",subtitle:"Mensalidades, pagamentos e documentos do contrato.",master:false,view:<FinanceView/>},
 creatives:{title:"Criativos",subtitle:"Navegue e baixe os materiais organizados pela NEX.",master:false,view:<CreativesView/>},
 users:{title:"Usuários",subtitle:"Gerencie acessos e permissões da sua equipe.",master:false,view:<UsersView/>},
 account:{title:"Minha conta",subtitle:"Preferências e dados do seu perfil.",master:false,view:<AccountView/>},
 blocked:{title:"Acesso suspenso",subtitle:"Estado de bloqueio por inadimplência após o terceiro dia.",master:false,view:<BlockedState/>},
 master:{title:"Operação NEX",subtitle:"Prioridades da operação em uma visão consolidada.",master:true,view:<MasterOverview/>},
 clients:{title:"Clientes",subtitle:"Gerencie contratos, acessos e situação de cada cliente.",master:true,view:<ClientsView/>},
 masterCampaigns:{title:"Campanhas globais",subtitle:"Monitore todos os clientes em somente leitura.",master:true,view:<CampaignsView/>},
 masterFinance:{title:"Financeiro Master",subtitle:"Acompanhe cobranças, recebimentos e inadimplência.",master:true,view:<MasterFinanceView/>},
 masterCreatives:{title:"Biblioteca de criativos",subtitle:"Organize materiais com isolamento por cliente.",master:true,view:<CreativesView master/>},
 settings:{title:"Configurações",subtitle:"Defina regras financeiras, integrações e mensagens.",master:true,view:<SettingsView/>},
 support:{title:"Modo suporte",subtitle:"Visualização auditada do ambiente de um cliente.",master:true,view:<SupportState/>},
} as const;
type ScreenKey=keyof typeof screens;

function DemoPage(){const [screen,setScreen]=useState<ScreenKey>("overview");const current=screens[screen];return <AppShell title={current.title} subtitle={current.subtitle} master={current.master}><Card className="mb-5 border-info/30 bg-info/5"><CardContent className="flex flex-col gap-3 p-4 sm:flex-row sm:items-center"><div className="flex-1"><p className="text-sm font-semibold">Navegar pela demonstração</p><p className="text-xs text-muted-foreground">Todas as telas estão disponíveis sem credenciais externas.</p></div><Select value={screen} onValueChange={value=>setScreen(value as ScreenKey)}><SelectTrigger className="w-full bg-background sm:w-72"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="overview">Cliente • Visão geral</SelectItem><SelectItem value="campaigns">Cliente • Campanhas</SelectItem><SelectItem value="credits">Cliente • Créditos Meta</SelectItem><SelectItem value="finance">Cliente • Financeiro</SelectItem><SelectItem value="creatives">Cliente • Criativos</SelectItem><SelectItem value="users">Cliente • Usuários</SelectItem><SelectItem value="account">Cliente • Minha conta</SelectItem><SelectItem value="blocked">Cliente • Acesso suspenso</SelectItem><SelectItem value="master">Master • Operação</SelectItem><SelectItem value="clients">Master • Clientes</SelectItem><SelectItem value="masterCampaigns">Master • Campanhas</SelectItem><SelectItem value="masterFinance">Master • Financeiro</SelectItem><SelectItem value="masterCreatives">Master • Criativos</SelectItem><SelectItem value="settings">Master • Configurações</SelectItem><SelectItem value="support">Master • Modo suporte</SelectItem></SelectContent></Select></CardContent></Card>{current.view}</AppShell>}

function BlockedState(){return <div className="relative min-h-[520px] overflow-hidden rounded-lg border"><div className="pointer-events-none grid gap-4 p-5 opacity-30 blur-sm sm:grid-cols-3">{[1,2,3,4,5,6].map(i=><Card key={i}><CardContent className="h-32 p-5"><div className="h-3 w-24 rounded bg-muted"/><div className="mt-5 h-8 w-36 rounded bg-muted"/></CardContent></Card>)}</div><div className="absolute inset-0 grid place-items-center bg-background/75 p-4"><Card className="w-full max-w-md shadow-panel"><CardContent className="p-6 text-center"><span className="mx-auto grid size-12 place-items-center rounded-full bg-destructive/10"><LockKeyhole className="size-6 text-destructive"/></span><h2 className="mt-4 font-display text-xl font-bold">Acesso temporariamente suspenso</h2><p className="mt-2 text-sm text-muted-foreground">Regularize o pagamento para recuperar automaticamente o acesso ao painel.</p><div className="my-5 rounded-lg bg-muted p-4"><p className="text-xs text-muted-foreground">Total devido</p><strong className="mt-1 block text-2xl">R$ 2.341,80</strong></div><Dialog><DialogTrigger asChild><Button className="w-full">Regularizar com Pix</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Regularização com Pix</DialogTitle><DialogDescription>O QR Code será criado pelo Asaas quando as credenciais estiverem configuradas.</DialogDescription></DialogHeader><div className="grid min-h-40 place-items-center rounded-lg border border-dashed"><p className="text-sm text-muted-foreground">Aguardando integração</p></div></DialogContent></Dialog></CardContent></Card></div></div>}

function SupportState(){return <div className="space-y-4"><div className="flex flex-col gap-3 rounded-lg border border-info/30 bg-info/10 p-4 sm:flex-row sm:items-center"><UserRoundCog className="size-5 text-info"/><div className="flex-1"><p className="font-semibold">Visualizando como Vértice Crédito</p><p className="text-sm text-muted-foreground">Acesso iniciado por Mariana Souza às 15:22 • ação registrada na auditoria</p></div><Button variant="outline"><ArrowLeft/>Voltar ao Master</Button></div><Overview/><div className="rounded-lg border p-4"><div className="flex gap-3"><AlertTriangle className="size-5 text-warning"/><div><p className="font-semibold">Sessão de suporte isolada</p><p className="text-sm text-muted-foreground">O acesso não altera a identidade do Master nem utiliza a senha do cliente.</p></div></div></div></div>}